### ISSUE TITLE
[enhancement] document dark mode auto switch

### ISSUE THREAD

**Issue by eshishki** [Emano-Waldeck/pdf-reader#28]
i love the ability to change content to dark mode as described in https://github.com/Emano-Waldeck/pdf-reader/issues/15

but i have to do it twice a day manually

i would love to save my dark mode config once and it to follow my global theme switch settings

**Comment by Emano-Waldeck** [comment]
You can use the `:root` selector, so that the canvas follows the selected dark/light theme.

```css
html[data-theme^="dark"] #viewerContainer > #viewer > .page > .canvasWrapper > canvas {
    filter: grayscale(100%);
    filter: invert(100%);
}
```

Using this code, you can use the right-click context menu to change the theme, or the extension follows the OS theme.
